### PR TITLE
Configurable AutoStationConfig

### PR DESCRIPTION
**Pull request by Pasukaru**

### CODE REVIEW

**Comment by alpe12** [comment]
Gigastations allow increments of 1% to Min. Load of Drones.
Shouldn't this mod allows 1% as well? Or would it cause problems if Gigastations is not installed?

**Comment by Pasukaru** [comment]
> 
> 
> `new AcceptableValueList<int>(1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100),`
> Gigastations allow increments of 1% to Min. Load of Drones.
> Shouldn't this mod allows 1% as well? Or would it cause problems if Gigastations is not installed?

Having full mod support is something for later. Will need to investigate if i can find out what the actual displays.
If the gigastations mod behaves the same way as vanilla, just with different values on the slider, than this will happen:
Via code, you can select a value that's not possible in the slider.
If this is the case, then it's displayed properly, but once you change it, you can't go back to that value.

Nothing should break though.

**Comment by alpe12** [comment]
> Via code, you can select a value that's not possible in the slider.
> If this is the case, then it's displayed properly, but once you change it, you can't go back to that value.
> Nothing should break though.
This is what I thought would happen.
If this is the case, it wouldn't be too bad to allow 1% increment even if gigastations is not installed.

Btw, when GigaStations is installed it allows 1% increments even on vanilla stations.

> Edit 2: Now i read it wrong. Increments of 1%.. yeah, not sure if/how to detect that. And how to reflect that in the r2modman config.
Yup.

**Comment by Pasukaru** [comment]
> If this is the case, it wouldn't be too bad to allow 1% increment even if gigastations is not installed.

Makes sense. I added it in.

**Comment by 3therios** [comment]
Good hustle and thanks for the credit!

in the interest of self improvement, is the rewriting  of how the config is initialised / setup to do with r2modman or is that C# convention that I am not aware of?

Also one minor typo, your comment above the Power / Charging says 60 MW, if I understood correctly, I assume you meant 300 MW?

**Comment by Pasukaru** [comment]
> Good hustle and thanks for the credit!

Sure

> in the interest of self improvement, is the rewriting of how the config is initialised / setup to do with r2modman or is that C# convention that I am not aware of?

As far as I know, all the configuration management is from BepInEx, and r2modman hooks into that during game start to generate the config files. Might be even BepInEx itself. I'm not entirely sure either.

**Pull request merged**
